defaultContentLanguage = "ja"
hasCJKLanguage = true
baseURL = 'https://klifehack.com/'
languageCode = 'ja'
title = 'K-Life Hack'
theme = 'hugo-theme-stack'
publishDir = 'docs'

# [1. 댓글 설정]
disqusShortname = "klifehack-com"

# [2. 분류 체계 정의]
[taxonomies]
    category = "categories"
    tag = "tags"

# [3. URL 구조]
[Permalinks]
    posts = "/p/:slug/"

[params]
    mainSections = ["posts"]
    featuredImageField = "image"
    favicon = "favicon.ico"

    [params.dateFormat]
        published = "2006/01/02"
        lastUpdated = "2006/01/02"

    [params.sidebar]
        avatar = "img/logo.jpg" 
        name = "K-Life Hack"
        subtitle = "韓国・パンギョの現役テクニカルアーティスト「K」による技術적キュレーション。最新ITトレンドからディープな旅行ハック、リアルな生活情報までお届けします。"

    [params.widgets]
        homepage = [
            { type = "search" },
            { type = "archives" },
            { type = "categories" }
        ]
        page = [
            { type = "toc" }
        ]

    [params.article]
        math = false
        toc = true
        readingTime = true

    [params.comments]
        enabled = true
        type = "disqus"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 10
        [menu.main.params]
            icon = "home"

    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 20
        [menu.main.params]
            icon = "archive" 

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/" 
        weight = 30
        [menu.main.params]
            icon = "user"

    [[menu.main]]
        identifier = "telegram"
        name = "Telegram"
        url = "https://t.me/korinside"
        weight = 40
        [menu.main.params]
            icon = "mail"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 2

[params.analytics]
    enable = true
    [params.analytics.google]
        id = "G-92N7W10SPC" 